version: '4'
services:
  server:
    build: 
     context: ./server
     dockerfile: DockerFile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    environment:
      - ./server/.env
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lms-networks

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - lms-networks

networks:
  lms-networks:
    driver: bridge