version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - lms-networks

  frontend:
    build: 
      context: ./frontend
      dockerfile: DockerFile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/.env.local:/app/frontend/.env.local
    environment:
      - NODE_ENV=development
      - /app/frontend/.env.local
    depends_on:
      - server
      - nginx

  server:
    build: 
      context: ./server
      dockerfile: DockerFile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/.env:/app/server/.env
    environment:
      - NODE_ENV=development
      - /app/server/.env
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lms-networks

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - lms-networks

networks:
  lms-networks:
    driver: bridge
