version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: DockerFile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/.env.local:/app/.env.local
    environment:
      - NODE_ENV=development
      - /app/.env.local
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: DockerFile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/.env:/app/.env
      - ./server/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - /app/.env
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

networks:
  lms-networks:
    driver: bridge
